version: '3.1'

services:

  db:
    image: postgres:11.1
    restart: always
    ports:
      - 3254:5432
    environment:
      POSTGRES_USER: Dmytr0
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: gophercises
